// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_speech_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_speech_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_speech_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_speech_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_speech_2eproto;
namespace mic_ser {
class SpeechRecognitionReq;
class SpeechRecognitionReqDefaultTypeInternal;
extern SpeechRecognitionReqDefaultTypeInternal _SpeechRecognitionReq_default_instance_;
class SpeechRecognitionRsp;
class SpeechRecognitionRspDefaultTypeInternal;
extern SpeechRecognitionRspDefaultTypeInternal _SpeechRecognitionRsp_default_instance_;
}  // namespace mic_ser
PROTOBUF_NAMESPACE_OPEN
template<> ::mic_ser::SpeechRecognitionReq* Arena::CreateMaybeMessage<::mic_ser::SpeechRecognitionReq>(Arena*);
template<> ::mic_ser::SpeechRecognitionRsp* Arena::CreateMaybeMessage<::mic_ser::SpeechRecognitionRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mic_ser {

// ===================================================================

class SpeechRecognitionReq :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mic_ser.SpeechRecognitionReq) */ {
 public:
  SpeechRecognitionReq();
  virtual ~SpeechRecognitionReq();

  SpeechRecognitionReq(const SpeechRecognitionReq& from);
  SpeechRecognitionReq(SpeechRecognitionReq&& from) noexcept
    : SpeechRecognitionReq() {
    *this = ::std::move(from);
  }

  inline SpeechRecognitionReq& operator=(const SpeechRecognitionReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpeechRecognitionReq& operator=(SpeechRecognitionReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SpeechRecognitionReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SpeechRecognitionReq* internal_default_instance() {
    return reinterpret_cast<const SpeechRecognitionReq*>(
               &_SpeechRecognitionReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SpeechRecognitionReq& a, SpeechRecognitionReq& b) {
    a.Swap(&b);
  }
  inline void Swap(SpeechRecognitionReq* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SpeechRecognitionReq* New() const final {
    return CreateMaybeMessage<SpeechRecognitionReq>(nullptr);
  }

  SpeechRecognitionReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SpeechRecognitionReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SpeechRecognitionReq& from);
  void MergeFrom(const SpeechRecognitionReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpeechRecognitionReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mic_ser.SpeechRecognitionReq";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speech_2eproto);
    return ::descriptor_table_speech_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestIdFieldNumber = 1,
    kSpeechDatasFieldNumber = 2,
    kUserIdFieldNumber = 3,
    kSessionIdFieldNumber = 4,
  };
  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  void set_request_id(const std::string& value);
  void set_request_id(std::string&& value);
  void set_request_id(const char* value);
  void set_request_id(const char* value, size_t size);
  std::string* mutable_request_id();
  std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // bytes speech_datas = 2;
  void clear_speech_datas();
  const std::string& speech_datas() const;
  void set_speech_datas(const std::string& value);
  void set_speech_datas(std::string&& value);
  void set_speech_datas(const char* value);
  void set_speech_datas(const void* value, size_t size);
  std::string* mutable_speech_datas();
  std::string* release_speech_datas();
  void set_allocated_speech_datas(std::string* speech_datas);
  private:
  const std::string& _internal_speech_datas() const;
  void _internal_set_speech_datas(const std::string& value);
  std::string* _internal_mutable_speech_datas();
  public:

  // string user_id = 3;
  void clear_user_id();
  const std::string& user_id() const;
  void set_user_id(const std::string& value);
  void set_user_id(std::string&& value);
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  std::string* mutable_user_id();
  std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // string session_id = 4;
  void clear_session_id();
  const std::string& session_id() const;
  void set_session_id(const std::string& value);
  void set_session_id(std::string&& value);
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  std::string* mutable_session_id();
  std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // @@protoc_insertion_point(class_scope:mic_ser.SpeechRecognitionReq)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr speech_datas_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speech_2eproto;
};
// -------------------------------------------------------------------

class SpeechRecognitionRsp :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mic_ser.SpeechRecognitionRsp) */ {
 public:
  SpeechRecognitionRsp();
  virtual ~SpeechRecognitionRsp();

  SpeechRecognitionRsp(const SpeechRecognitionRsp& from);
  SpeechRecognitionRsp(SpeechRecognitionRsp&& from) noexcept
    : SpeechRecognitionRsp() {
    *this = ::std::move(from);
  }

  inline SpeechRecognitionRsp& operator=(const SpeechRecognitionRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpeechRecognitionRsp& operator=(SpeechRecognitionRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SpeechRecognitionRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SpeechRecognitionRsp* internal_default_instance() {
    return reinterpret_cast<const SpeechRecognitionRsp*>(
               &_SpeechRecognitionRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SpeechRecognitionRsp& a, SpeechRecognitionRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(SpeechRecognitionRsp* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SpeechRecognitionRsp* New() const final {
    return CreateMaybeMessage<SpeechRecognitionRsp>(nullptr);
  }

  SpeechRecognitionRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SpeechRecognitionRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SpeechRecognitionRsp& from);
  void MergeFrom(const SpeechRecognitionRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpeechRecognitionRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mic_ser.SpeechRecognitionRsp";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speech_2eproto);
    return ::descriptor_table_speech_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResponseIdFieldNumber = 1,
    kErrmsgFieldNumber = 3,
    kRecognitionResultFieldNumber = 4,
    kSuccessFieldNumber = 2,
  };
  // string response_id = 1;
  void clear_response_id();
  const std::string& response_id() const;
  void set_response_id(const std::string& value);
  void set_response_id(std::string&& value);
  void set_response_id(const char* value);
  void set_response_id(const char* value, size_t size);
  std::string* mutable_response_id();
  std::string* release_response_id();
  void set_allocated_response_id(std::string* response_id);
  private:
  const std::string& _internal_response_id() const;
  void _internal_set_response_id(const std::string& value);
  std::string* _internal_mutable_response_id();
  public:

  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const char* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // string recognition_result = 4;
  void clear_recognition_result();
  const std::string& recognition_result() const;
  void set_recognition_result(const std::string& value);
  void set_recognition_result(std::string&& value);
  void set_recognition_result(const char* value);
  void set_recognition_result(const char* value, size_t size);
  std::string* mutable_recognition_result();
  std::string* release_recognition_result();
  void set_allocated_recognition_result(std::string* recognition_result);
  private:
  const std::string& _internal_recognition_result() const;
  void _internal_set_recognition_result(const std::string& value);
  std::string* _internal_mutable_recognition_result();
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:mic_ser.SpeechRecognitionRsp)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr response_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr recognition_result_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speech_2eproto;
};
// ===================================================================

class SpeechService_Stub;

class SpeechService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline SpeechService() {};
 public:
  virtual ~SpeechService();

  typedef SpeechService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void SpeechRecogntion(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::mic_ser::SpeechRecognitionReq* request,
                       ::mic_ser::SpeechRecognitionRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(SpeechService);
};

class SpeechService_Stub : public SpeechService {
 public:
  SpeechService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  SpeechService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~SpeechService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements SpeechService ------------------------------------------

  void SpeechRecogntion(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::mic_ser::SpeechRecognitionReq* request,
                       ::mic_ser::SpeechRecognitionRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(SpeechService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SpeechRecognitionReq

// string request_id = 1;
inline void SpeechRecognitionReq::clear_request_id() {
  request_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SpeechRecognitionReq::request_id() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionReq.request_id)
  return _internal_request_id();
}
inline void SpeechRecognitionReq::set_request_id(const std::string& value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionReq.request_id)
}
inline std::string* SpeechRecognitionReq::mutable_request_id() {
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionReq.request_id)
  return _internal_mutable_request_id();
}
inline const std::string& SpeechRecognitionReq::_internal_request_id() const {
  return request_id_.GetNoArena();
}
inline void SpeechRecognitionReq::_internal_set_request_id(const std::string& value) {
  
  request_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void SpeechRecognitionReq::set_request_id(std::string&& value) {
  
  request_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mic_ser.SpeechRecognitionReq.request_id)
}
inline void SpeechRecognitionReq::set_request_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  request_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mic_ser.SpeechRecognitionReq.request_id)
}
inline void SpeechRecognitionReq::set_request_id(const char* value, size_t size) {
  
  request_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mic_ser.SpeechRecognitionReq.request_id)
}
inline std::string* SpeechRecognitionReq::_internal_mutable_request_id() {
  
  return request_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SpeechRecognitionReq::release_request_id() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionReq.request_id)
  
  return request_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SpeechRecognitionReq::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  request_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), request_id);
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionReq.request_id)
}

// bytes speech_datas = 2;
inline void SpeechRecognitionReq::clear_speech_datas() {
  speech_datas_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SpeechRecognitionReq::speech_datas() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionReq.speech_datas)
  return _internal_speech_datas();
}
inline void SpeechRecognitionReq::set_speech_datas(const std::string& value) {
  _internal_set_speech_datas(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionReq.speech_datas)
}
inline std::string* SpeechRecognitionReq::mutable_speech_datas() {
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionReq.speech_datas)
  return _internal_mutable_speech_datas();
}
inline const std::string& SpeechRecognitionReq::_internal_speech_datas() const {
  return speech_datas_.GetNoArena();
}
inline void SpeechRecognitionReq::_internal_set_speech_datas(const std::string& value) {
  
  speech_datas_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void SpeechRecognitionReq::set_speech_datas(std::string&& value) {
  
  speech_datas_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mic_ser.SpeechRecognitionReq.speech_datas)
}
inline void SpeechRecognitionReq::set_speech_datas(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  speech_datas_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mic_ser.SpeechRecognitionReq.speech_datas)
}
inline void SpeechRecognitionReq::set_speech_datas(const void* value, size_t size) {
  
  speech_datas_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mic_ser.SpeechRecognitionReq.speech_datas)
}
inline std::string* SpeechRecognitionReq::_internal_mutable_speech_datas() {
  
  return speech_datas_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SpeechRecognitionReq::release_speech_datas() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionReq.speech_datas)
  
  return speech_datas_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SpeechRecognitionReq::set_allocated_speech_datas(std::string* speech_datas) {
  if (speech_datas != nullptr) {
    
  } else {
    
  }
  speech_datas_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), speech_datas);
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionReq.speech_datas)
}

// string user_id = 3;
inline void SpeechRecognitionReq::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SpeechRecognitionReq::user_id() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionReq.user_id)
  return _internal_user_id();
}
inline void SpeechRecognitionReq::set_user_id(const std::string& value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionReq.user_id)
}
inline std::string* SpeechRecognitionReq::mutable_user_id() {
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionReq.user_id)
  return _internal_mutable_user_id();
}
inline const std::string& SpeechRecognitionReq::_internal_user_id() const {
  return user_id_.GetNoArena();
}
inline void SpeechRecognitionReq::_internal_set_user_id(const std::string& value) {
  
  user_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void SpeechRecognitionReq::set_user_id(std::string&& value) {
  
  user_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mic_ser.SpeechRecognitionReq.user_id)
}
inline void SpeechRecognitionReq::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  user_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mic_ser.SpeechRecognitionReq.user_id)
}
inline void SpeechRecognitionReq::set_user_id(const char* value, size_t size) {
  
  user_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mic_ser.SpeechRecognitionReq.user_id)
}
inline std::string* SpeechRecognitionReq::_internal_mutable_user_id() {
  
  return user_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SpeechRecognitionReq::release_user_id() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionReq.user_id)
  
  return user_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SpeechRecognitionReq::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  user_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionReq.user_id)
}

// string session_id = 4;
inline void SpeechRecognitionReq::clear_session_id() {
  session_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SpeechRecognitionReq::session_id() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionReq.session_id)
  return _internal_session_id();
}
inline void SpeechRecognitionReq::set_session_id(const std::string& value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionReq.session_id)
}
inline std::string* SpeechRecognitionReq::mutable_session_id() {
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionReq.session_id)
  return _internal_mutable_session_id();
}
inline const std::string& SpeechRecognitionReq::_internal_session_id() const {
  return session_id_.GetNoArena();
}
inline void SpeechRecognitionReq::_internal_set_session_id(const std::string& value) {
  
  session_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void SpeechRecognitionReq::set_session_id(std::string&& value) {
  
  session_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mic_ser.SpeechRecognitionReq.session_id)
}
inline void SpeechRecognitionReq::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  session_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mic_ser.SpeechRecognitionReq.session_id)
}
inline void SpeechRecognitionReq::set_session_id(const char* value, size_t size) {
  
  session_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mic_ser.SpeechRecognitionReq.session_id)
}
inline std::string* SpeechRecognitionReq::_internal_mutable_session_id() {
  
  return session_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SpeechRecognitionReq::release_session_id() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionReq.session_id)
  
  return session_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SpeechRecognitionReq::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), session_id);
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionReq.session_id)
}

// -------------------------------------------------------------------

// SpeechRecognitionRsp

// string response_id = 1;
inline void SpeechRecognitionRsp::clear_response_id() {
  response_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SpeechRecognitionRsp::response_id() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionRsp.response_id)
  return _internal_response_id();
}
inline void SpeechRecognitionRsp::set_response_id(const std::string& value) {
  _internal_set_response_id(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionRsp.response_id)
}
inline std::string* SpeechRecognitionRsp::mutable_response_id() {
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionRsp.response_id)
  return _internal_mutable_response_id();
}
inline const std::string& SpeechRecognitionRsp::_internal_response_id() const {
  return response_id_.GetNoArena();
}
inline void SpeechRecognitionRsp::_internal_set_response_id(const std::string& value) {
  
  response_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void SpeechRecognitionRsp::set_response_id(std::string&& value) {
  
  response_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mic_ser.SpeechRecognitionRsp.response_id)
}
inline void SpeechRecognitionRsp::set_response_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  response_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mic_ser.SpeechRecognitionRsp.response_id)
}
inline void SpeechRecognitionRsp::set_response_id(const char* value, size_t size) {
  
  response_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mic_ser.SpeechRecognitionRsp.response_id)
}
inline std::string* SpeechRecognitionRsp::_internal_mutable_response_id() {
  
  return response_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SpeechRecognitionRsp::release_response_id() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionRsp.response_id)
  
  return response_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SpeechRecognitionRsp::set_allocated_response_id(std::string* response_id) {
  if (response_id != nullptr) {
    
  } else {
    
  }
  response_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), response_id);
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionRsp.response_id)
}

// bool success = 2;
inline void SpeechRecognitionRsp::clear_success() {
  success_ = false;
}
inline bool SpeechRecognitionRsp::_internal_success() const {
  return success_;
}
inline bool SpeechRecognitionRsp::success() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionRsp.success)
  return _internal_success();
}
inline void SpeechRecognitionRsp::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void SpeechRecognitionRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionRsp.success)
}

// string errmsg = 3;
inline void SpeechRecognitionRsp::clear_errmsg() {
  errmsg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SpeechRecognitionRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionRsp.errmsg)
  return _internal_errmsg();
}
inline void SpeechRecognitionRsp::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionRsp.errmsg)
}
inline std::string* SpeechRecognitionRsp::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionRsp.errmsg)
  return _internal_mutable_errmsg();
}
inline const std::string& SpeechRecognitionRsp::_internal_errmsg() const {
  return errmsg_.GetNoArena();
}
inline void SpeechRecognitionRsp::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void SpeechRecognitionRsp::set_errmsg(std::string&& value) {
  
  errmsg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mic_ser.SpeechRecognitionRsp.errmsg)
}
inline void SpeechRecognitionRsp::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mic_ser.SpeechRecognitionRsp.errmsg)
}
inline void SpeechRecognitionRsp::set_errmsg(const char* value, size_t size) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mic_ser.SpeechRecognitionRsp.errmsg)
}
inline std::string* SpeechRecognitionRsp::_internal_mutable_errmsg() {
  
  return errmsg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SpeechRecognitionRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionRsp.errmsg)
  
  return errmsg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SpeechRecognitionRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg);
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionRsp.errmsg)
}

// string recognition_result = 4;
inline void SpeechRecognitionRsp::clear_recognition_result() {
  recognition_result_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SpeechRecognitionRsp::recognition_result() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionRsp.recognition_result)
  return _internal_recognition_result();
}
inline void SpeechRecognitionRsp::set_recognition_result(const std::string& value) {
  _internal_set_recognition_result(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionRsp.recognition_result)
}
inline std::string* SpeechRecognitionRsp::mutable_recognition_result() {
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionRsp.recognition_result)
  return _internal_mutable_recognition_result();
}
inline const std::string& SpeechRecognitionRsp::_internal_recognition_result() const {
  return recognition_result_.GetNoArena();
}
inline void SpeechRecognitionRsp::_internal_set_recognition_result(const std::string& value) {
  
  recognition_result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void SpeechRecognitionRsp::set_recognition_result(std::string&& value) {
  
  recognition_result_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mic_ser.SpeechRecognitionRsp.recognition_result)
}
inline void SpeechRecognitionRsp::set_recognition_result(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  recognition_result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mic_ser.SpeechRecognitionRsp.recognition_result)
}
inline void SpeechRecognitionRsp::set_recognition_result(const char* value, size_t size) {
  
  recognition_result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mic_ser.SpeechRecognitionRsp.recognition_result)
}
inline std::string* SpeechRecognitionRsp::_internal_mutable_recognition_result() {
  
  return recognition_result_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SpeechRecognitionRsp::release_recognition_result() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionRsp.recognition_result)
  
  return recognition_result_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SpeechRecognitionRsp::set_allocated_recognition_result(std::string* recognition_result) {
  if (recognition_result != nullptr) {
    
  } else {
    
  }
  recognition_result_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), recognition_result);
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionRsp.recognition_result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mic_ser

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_speech_2eproto
