// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_speech_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_speech_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_speech_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_speech_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_speech_2eproto;
namespace mic_ser {
class SpeechRecognitionReq;
struct SpeechRecognitionReqDefaultTypeInternal;
extern SpeechRecognitionReqDefaultTypeInternal _SpeechRecognitionReq_default_instance_;
class SpeechRecognitionRsp;
struct SpeechRecognitionRspDefaultTypeInternal;
extern SpeechRecognitionRspDefaultTypeInternal _SpeechRecognitionRsp_default_instance_;
}  // namespace mic_ser
PROTOBUF_NAMESPACE_OPEN
template<> ::mic_ser::SpeechRecognitionReq* Arena::CreateMaybeMessage<::mic_ser::SpeechRecognitionReq>(Arena*);
template<> ::mic_ser::SpeechRecognitionRsp* Arena::CreateMaybeMessage<::mic_ser::SpeechRecognitionRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mic_ser {

// ===================================================================

class SpeechRecognitionReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mic_ser.SpeechRecognitionReq) */ {
 public:
  inline SpeechRecognitionReq() : SpeechRecognitionReq(nullptr) {}
  ~SpeechRecognitionReq() override;
  explicit PROTOBUF_CONSTEXPR SpeechRecognitionReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpeechRecognitionReq(const SpeechRecognitionReq& from);
  SpeechRecognitionReq(SpeechRecognitionReq&& from) noexcept
    : SpeechRecognitionReq() {
    *this = ::std::move(from);
  }

  inline SpeechRecognitionReq& operator=(const SpeechRecognitionReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpeechRecognitionReq& operator=(SpeechRecognitionReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpeechRecognitionReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpeechRecognitionReq* internal_default_instance() {
    return reinterpret_cast<const SpeechRecognitionReq*>(
               &_SpeechRecognitionReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SpeechRecognitionReq& a, SpeechRecognitionReq& b) {
    a.Swap(&b);
  }
  inline void Swap(SpeechRecognitionReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpeechRecognitionReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpeechRecognitionReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpeechRecognitionReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpeechRecognitionReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpeechRecognitionReq& from) {
    SpeechRecognitionReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpeechRecognitionReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mic_ser.SpeechRecognitionReq";
  }
  protected:
  explicit SpeechRecognitionReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestIdFieldNumber = 1,
    kSpeechDatasFieldNumber = 2,
    kUserIdFieldNumber = 3,
    kSessionIdFieldNumber = 4,
  };
  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request_id();
  PROTOBUF_NODISCARD std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // bytes speech_datas = 2;
  void clear_speech_datas();
  const std::string& speech_datas() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_speech_datas(ArgT0&& arg0, ArgT... args);
  std::string* mutable_speech_datas();
  PROTOBUF_NODISCARD std::string* release_speech_datas();
  void set_allocated_speech_datas(std::string* speech_datas);
  private:
  const std::string& _internal_speech_datas() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_speech_datas(const std::string& value);
  std::string* _internal_mutable_speech_datas();
  public:

  // string user_id = 3;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // string session_id = 4;
  void clear_session_id();
  const std::string& session_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_id();
  PROTOBUF_NODISCARD std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // @@protoc_insertion_point(class_scope:mic_ser.SpeechRecognitionReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr speech_datas_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_speech_2eproto;
};
// -------------------------------------------------------------------

class SpeechRecognitionRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mic_ser.SpeechRecognitionRsp) */ {
 public:
  inline SpeechRecognitionRsp() : SpeechRecognitionRsp(nullptr) {}
  ~SpeechRecognitionRsp() override;
  explicit PROTOBUF_CONSTEXPR SpeechRecognitionRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpeechRecognitionRsp(const SpeechRecognitionRsp& from);
  SpeechRecognitionRsp(SpeechRecognitionRsp&& from) noexcept
    : SpeechRecognitionRsp() {
    *this = ::std::move(from);
  }

  inline SpeechRecognitionRsp& operator=(const SpeechRecognitionRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpeechRecognitionRsp& operator=(SpeechRecognitionRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpeechRecognitionRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpeechRecognitionRsp* internal_default_instance() {
    return reinterpret_cast<const SpeechRecognitionRsp*>(
               &_SpeechRecognitionRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SpeechRecognitionRsp& a, SpeechRecognitionRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(SpeechRecognitionRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpeechRecognitionRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpeechRecognitionRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpeechRecognitionRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpeechRecognitionRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpeechRecognitionRsp& from) {
    SpeechRecognitionRsp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpeechRecognitionRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mic_ser.SpeechRecognitionRsp";
  }
  protected:
  explicit SpeechRecognitionRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResponseIdFieldNumber = 1,
    kErrmsgFieldNumber = 3,
    kRecognitionResultFieldNumber = 4,
    kSuccessFieldNumber = 2,
  };
  // string response_id = 1;
  void clear_response_id();
  const std::string& response_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_response_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_response_id();
  PROTOBUF_NODISCARD std::string* release_response_id();
  void set_allocated_response_id(std::string* response_id);
  private:
  const std::string& _internal_response_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_response_id(const std::string& value);
  std::string* _internal_mutable_response_id();
  public:

  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_NODISCARD std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // string recognition_result = 4;
  void clear_recognition_result();
  const std::string& recognition_result() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_recognition_result(ArgT0&& arg0, ArgT... args);
  std::string* mutable_recognition_result();
  PROTOBUF_NODISCARD std::string* release_recognition_result();
  void set_allocated_recognition_result(std::string* recognition_result);
  private:
  const std::string& _internal_recognition_result() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_recognition_result(const std::string& value);
  std::string* _internal_mutable_recognition_result();
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:mic_ser.SpeechRecognitionRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr response_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr recognition_result_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_speech_2eproto;
};
// ===================================================================

class SpeechService_Stub;

class SpeechService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline SpeechService() {};
 public:
  virtual ~SpeechService();

  typedef SpeechService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void SpeechRecognition(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::mic_ser::SpeechRecognitionReq* request,
                       ::mic_ser::SpeechRecognitionRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(SpeechService);
};

class SpeechService_Stub : public SpeechService {
 public:
  SpeechService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  SpeechService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~SpeechService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements SpeechService ------------------------------------------

  void SpeechRecognition(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::mic_ser::SpeechRecognitionReq* request,
                       ::mic_ser::SpeechRecognitionRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(SpeechService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SpeechRecognitionReq

// string request_id = 1;
inline void SpeechRecognitionReq::clear_request_id() {
  _impl_.request_id_.ClearToEmpty();
}
inline const std::string& SpeechRecognitionReq::request_id() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionReq.request_id)
  return _internal_request_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpeechRecognitionReq::set_request_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.request_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionReq.request_id)
}
inline std::string* SpeechRecognitionReq::mutable_request_id() {
  std::string* _s = _internal_mutable_request_id();
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionReq.request_id)
  return _s;
}
inline const std::string& SpeechRecognitionReq::_internal_request_id() const {
  return _impl_.request_id_.Get();
}
inline void SpeechRecognitionReq::_internal_set_request_id(const std::string& value) {
  
  _impl_.request_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SpeechRecognitionReq::_internal_mutable_request_id() {
  
  return _impl_.request_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SpeechRecognitionReq::release_request_id() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionReq.request_id)
  return _impl_.request_id_.Release();
}
inline void SpeechRecognitionReq::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  _impl_.request_id_.SetAllocated(request_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.request_id_.IsDefault()) {
    _impl_.request_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionReq.request_id)
}

// bytes speech_datas = 2;
inline void SpeechRecognitionReq::clear_speech_datas() {
  _impl_.speech_datas_.ClearToEmpty();
}
inline const std::string& SpeechRecognitionReq::speech_datas() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionReq.speech_datas)
  return _internal_speech_datas();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpeechRecognitionReq::set_speech_datas(ArgT0&& arg0, ArgT... args) {
 
 _impl_.speech_datas_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionReq.speech_datas)
}
inline std::string* SpeechRecognitionReq::mutable_speech_datas() {
  std::string* _s = _internal_mutable_speech_datas();
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionReq.speech_datas)
  return _s;
}
inline const std::string& SpeechRecognitionReq::_internal_speech_datas() const {
  return _impl_.speech_datas_.Get();
}
inline void SpeechRecognitionReq::_internal_set_speech_datas(const std::string& value) {
  
  _impl_.speech_datas_.Set(value, GetArenaForAllocation());
}
inline std::string* SpeechRecognitionReq::_internal_mutable_speech_datas() {
  
  return _impl_.speech_datas_.Mutable(GetArenaForAllocation());
}
inline std::string* SpeechRecognitionReq::release_speech_datas() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionReq.speech_datas)
  return _impl_.speech_datas_.Release();
}
inline void SpeechRecognitionReq::set_allocated_speech_datas(std::string* speech_datas) {
  if (speech_datas != nullptr) {
    
  } else {
    
  }
  _impl_.speech_datas_.SetAllocated(speech_datas, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.speech_datas_.IsDefault()) {
    _impl_.speech_datas_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionReq.speech_datas)
}

// string user_id = 3;
inline void SpeechRecognitionReq::clear_user_id() {
  _impl_.user_id_.ClearToEmpty();
}
inline const std::string& SpeechRecognitionReq::user_id() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionReq.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpeechRecognitionReq::set_user_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionReq.user_id)
}
inline std::string* SpeechRecognitionReq::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionReq.user_id)
  return _s;
}
inline const std::string& SpeechRecognitionReq::_internal_user_id() const {
  return _impl_.user_id_.Get();
}
inline void SpeechRecognitionReq::_internal_set_user_id(const std::string& value) {
  
  _impl_.user_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SpeechRecognitionReq::_internal_mutable_user_id() {
  
  return _impl_.user_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SpeechRecognitionReq::release_user_id() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionReq.user_id)
  return _impl_.user_id_.Release();
}
inline void SpeechRecognitionReq::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  _impl_.user_id_.SetAllocated(user_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionReq.user_id)
}

// string session_id = 4;
inline void SpeechRecognitionReq::clear_session_id() {
  _impl_.session_id_.ClearToEmpty();
}
inline const std::string& SpeechRecognitionReq::session_id() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionReq.session_id)
  return _internal_session_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpeechRecognitionReq::set_session_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionReq.session_id)
}
inline std::string* SpeechRecognitionReq::mutable_session_id() {
  std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionReq.session_id)
  return _s;
}
inline const std::string& SpeechRecognitionReq::_internal_session_id() const {
  return _impl_.session_id_.Get();
}
inline void SpeechRecognitionReq::_internal_set_session_id(const std::string& value) {
  
  _impl_.session_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SpeechRecognitionReq::_internal_mutable_session_id() {
  
  return _impl_.session_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SpeechRecognitionReq::release_session_id() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionReq.session_id)
  return _impl_.session_id_.Release();
}
inline void SpeechRecognitionReq::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  _impl_.session_id_.SetAllocated(session_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionReq.session_id)
}

// -------------------------------------------------------------------

// SpeechRecognitionRsp

// string response_id = 1;
inline void SpeechRecognitionRsp::clear_response_id() {
  _impl_.response_id_.ClearToEmpty();
}
inline const std::string& SpeechRecognitionRsp::response_id() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionRsp.response_id)
  return _internal_response_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpeechRecognitionRsp::set_response_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.response_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionRsp.response_id)
}
inline std::string* SpeechRecognitionRsp::mutable_response_id() {
  std::string* _s = _internal_mutable_response_id();
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionRsp.response_id)
  return _s;
}
inline const std::string& SpeechRecognitionRsp::_internal_response_id() const {
  return _impl_.response_id_.Get();
}
inline void SpeechRecognitionRsp::_internal_set_response_id(const std::string& value) {
  
  _impl_.response_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SpeechRecognitionRsp::_internal_mutable_response_id() {
  
  return _impl_.response_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SpeechRecognitionRsp::release_response_id() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionRsp.response_id)
  return _impl_.response_id_.Release();
}
inline void SpeechRecognitionRsp::set_allocated_response_id(std::string* response_id) {
  if (response_id != nullptr) {
    
  } else {
    
  }
  _impl_.response_id_.SetAllocated(response_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.response_id_.IsDefault()) {
    _impl_.response_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionRsp.response_id)
}

// bool success = 2;
inline void SpeechRecognitionRsp::clear_success() {
  _impl_.success_ = false;
}
inline bool SpeechRecognitionRsp::_internal_success() const {
  return _impl_.success_;
}
inline bool SpeechRecognitionRsp::success() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionRsp.success)
  return _internal_success();
}
inline void SpeechRecognitionRsp::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void SpeechRecognitionRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionRsp.success)
}

// string errmsg = 3;
inline void SpeechRecognitionRsp::clear_errmsg() {
  _impl_.errmsg_.ClearToEmpty();
}
inline const std::string& SpeechRecognitionRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionRsp.errmsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpeechRecognitionRsp::set_errmsg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errmsg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionRsp.errmsg)
}
inline std::string* SpeechRecognitionRsp::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionRsp.errmsg)
  return _s;
}
inline const std::string& SpeechRecognitionRsp::_internal_errmsg() const {
  return _impl_.errmsg_.Get();
}
inline void SpeechRecognitionRsp::_internal_set_errmsg(const std::string& value) {
  
  _impl_.errmsg_.Set(value, GetArenaForAllocation());
}
inline std::string* SpeechRecognitionRsp::_internal_mutable_errmsg() {
  
  return _impl_.errmsg_.Mutable(GetArenaForAllocation());
}
inline std::string* SpeechRecognitionRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionRsp.errmsg)
  return _impl_.errmsg_.Release();
}
inline void SpeechRecognitionRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  _impl_.errmsg_.SetAllocated(errmsg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errmsg_.IsDefault()) {
    _impl_.errmsg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionRsp.errmsg)
}

// string recognition_result = 4;
inline void SpeechRecognitionRsp::clear_recognition_result() {
  _impl_.recognition_result_.ClearToEmpty();
}
inline const std::string& SpeechRecognitionRsp::recognition_result() const {
  // @@protoc_insertion_point(field_get:mic_ser.SpeechRecognitionRsp.recognition_result)
  return _internal_recognition_result();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpeechRecognitionRsp::set_recognition_result(ArgT0&& arg0, ArgT... args) {
 
 _impl_.recognition_result_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mic_ser.SpeechRecognitionRsp.recognition_result)
}
inline std::string* SpeechRecognitionRsp::mutable_recognition_result() {
  std::string* _s = _internal_mutable_recognition_result();
  // @@protoc_insertion_point(field_mutable:mic_ser.SpeechRecognitionRsp.recognition_result)
  return _s;
}
inline const std::string& SpeechRecognitionRsp::_internal_recognition_result() const {
  return _impl_.recognition_result_.Get();
}
inline void SpeechRecognitionRsp::_internal_set_recognition_result(const std::string& value) {
  
  _impl_.recognition_result_.Set(value, GetArenaForAllocation());
}
inline std::string* SpeechRecognitionRsp::_internal_mutable_recognition_result() {
  
  return _impl_.recognition_result_.Mutable(GetArenaForAllocation());
}
inline std::string* SpeechRecognitionRsp::release_recognition_result() {
  // @@protoc_insertion_point(field_release:mic_ser.SpeechRecognitionRsp.recognition_result)
  return _impl_.recognition_result_.Release();
}
inline void SpeechRecognitionRsp::set_allocated_recognition_result(std::string* recognition_result) {
  if (recognition_result != nullptr) {
    
  } else {
    
  }
  _impl_.recognition_result_.SetAllocated(recognition_result, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.recognition_result_.IsDefault()) {
    _impl_.recognition_result_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mic_ser.SpeechRecognitionRsp.recognition_result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mic_ser

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_speech_2eproto
